apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic
  namespace: petclinic
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi