---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
data:
  JDBC_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMucG9zdGdyZXMuc3ZjLmxvY2FsOjU0MzIvcGV0Y2xpbmlj
  PETCLINIC_JDBC_USER: cGV0Y2xpbmlj
  PETCLINIC_JDBC_PASSWORD: MTIzNDU2Nzg=