apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
spec:
  selector:
    app: petclinic
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
