apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 070387/spring-petclinic:latest
        ports:
        - containerPort: 8080          
          name: web
        env:
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: JDBC_URL
        - name: PETCLINIC_JDBC_USER
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: PETCLINIC_JDBC_USER
        - name: PETCLINIC_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: petclinic-secret
              key: PETCLINIC_JDBC_PASSWORD          
        volumeMounts:
        - mountPath: /bindings/secret
          name: petclinic
          readOnly: false
      volumes:
      - name: petclinic
        persistentVolumeClaim:
          claimName: petclinic
        
