receivers:
  - name: 'telegram'
    webhook_configs:
      - url: 'https://api.telegram.org/bot<bot_token>/sendMessage?chat_id=<chat_id>&text=DockerContainerUsage CPU load 87%'
route:
  receiver: 'telegram'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: warning
      receiver: 'telegram'
