version: '3.8' 
networks: 
  monitoring: 
    driver: bridge 
volumes: 
  prometheus_data: {}
  alertmanager_data: {}
 
services: 
  node-exporter: 
    image: prom/node-exporter:latest 
    container_name: node-exporter 
    restart: unless-stopped 
    volumes: 
      - /proc:/host/proc:ro 
      - /sys:/host/sys:ro 
      - /:/rootfs:ro 
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.rootfs=/rootfs' 
      - '--path.sysfs=/host/sys' 
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)' 
    ports: 
      - 9100:9100 
    networks: 
      - monitoring 
  prometheus: 
    image: prom/prometheus:latest 
    user: "1000" 
    environment: 
      - PUID=1000 
      - PGID=1000 
    container_name: prometheus 
    restart: unless-stopped 
    volumes: 
      - ~/promgrafnode/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/promgrafnode/prometheus/rules.yml:/etc/prometheus/rules.yml 
      - ~/promgrafnode/prometheus:/prometheus 
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus' 
      - '--web.console.libraries=/etc/prometheus/console_libraries' 
      - '--web.console.templates=/etc/prometheus/consoles' 
      - '--web.enable-lifecycle' 
    ports: 
      - 9090:9090 
    networks: 
      - monitoring 
  grafana: 
    image: grafana/grafana:latest 
    user: "1000" 
    container_name: grafana 
    ports: 
      - 3000:3000 
    restart: unless-stopped 
    volumes: 
      - ~/promgrafnode/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources 
      - ~/promgrafnode/grafana:/var/lib/grafana
    networks: 
      - monitoring 
  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    ports: 
      - 8081:8080 
    networks: 
      - monitoring 
    volumes: 
      - /:/rootfs:ro 
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    depends_on: 
      - redis 
  redis: 
    image: redis:latest 
    container_name: redis 
    ports: 
      - 6379:6379 
    networks: 
      - monitoring
 
  alertmanager: 
    image: quay.io/prometheus/alertmanager:latest 
    user: "1000" 
    environment: 
      - PUID=1000 
      - PGID=1000 
    container_name: alertmanager 
    restart: unless-stopped 
    volumes: 
      - ~/promgrafnode/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml 
      - ~/promgrafnode/alertmanager:/alertmanager 
    ports: 
      - 9093:9093 
    networks: 
      - monitoring 
  loki:
    image: grafana/loki:2.9.4
    user: "1000"
    environment:
      - PUID=1000
      - PGID=1000
    container_name: loki
    restart: unless-stopped
    volumes: 
      - ~/promgrafnode/loki/loki-config.yml:/etc/loki/loki-config.yml 
      - ~/promgrafnode/loki:/loki 
    ports:
      - "3100:3100"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.4
    user: "1000"
    environment:
      - PUID=1000
      - PGID=1000
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - ~/promgrafnode/loki/promtail-config.yml:/etc/loki/promtail-config.yml
    networks:
      - monitoring
