---
- name: Install common packages
  hosts: backend
  become: yes #to run tasks with sudo

  tasks:
   - name: Update package cache
     apt:
       update_cache: yes
     when: ansible_os_family == 'Debian' #Use 'yum' for Red Hat based systems

   - name: remove added user 
     ansible.builtin.user:
       name: hillel
       state: absent
       remove: true
       

   - name: Install Nginx
     package:
       name: nginx
       state: absent

   - name: Install Git
     package:
       name: git
       state: absent

   - name: Install Zip
     package:
       name: zip
       state: absent 