name: Docker Image CI


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code
      
    - name: Build Docker Image
      id: buildAndPushImage
      uses: abhishek-070/docker-image-build-push-action@v1.0
      with:
          registry_url: 'docker.io'
          repository_name: 'demo-app'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: 'v1.0'
          docker_file: 'docker'
    - name: Get pre step result output image_pull_url
      run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
      
   
    

