name: Docker Image CI


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code
      
    - name: Build and Push Container to docker.io
      uses: GlueOps/github-actions-build-push-containers@v0.3.6
      with:
          registry: "docker.io"
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
    

