name: Docker Image CI


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checout@v3
    - name: Build the Docker image
      run: docker build . --file docker/dockerfile -- tag cicd-practice:$(date +%s)

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: 070387/cicd-practice:$(date +%s)
        registry: docker.io
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

