name: Docker Image CI


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: 070387/git
        tags: v1
        dockerfile: docker/dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
   
    

