name: Docker Image CI


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: docker
      run: docker build . --file dockerfile --tag cicd-practice:$(date +%s)

   - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: 070387/cicd-practice:$(date +%s)
        registry: docker.io
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

